### ISSUE TITLE
why font size needs to be forced?

### ISSUE THREAD

**Issue by erikdemarco** [leemunroe/responsive-html-email-template#98]
Because of this line:

```
        table[class=body] a {
          font-size: 16px !important; /* why this needs to be important??? */
        }
```
We cant modify our fontsize in the email. Please remove that !important

**Comment by leemunroe** [comment]
It has been a while since I tested this but I believe `!important` is required for media queries as you want to override the inlined style. Without it, the inline style would take precedence. Please correct me if I'm wrong.

If you want a different responsive/mobile font-size you should change this value.
